[package]
name = "opensearch-sync-prototype"
version = "0.1.0"
edition = "2024"

[dependencies]
aws-config = "1.8.2"
opensearch = {version="2.3.0", features= ["aws-auth"]}
serde = "1.0.219"
serde_json = "1.0.141"
tokio = { version = "1.46.1", features = ["full"] }
uuid = "1.17.0"
